export const culturalActivities =[
    {
        id:1,
        name:"Baile",
        icon:"woman"
    },
    {
        id:2,
        name:"Ballet",
        icon:"woman"
    },
    {
        id:3,
        name:"Piano",
        icon:"musical-notes"
    },
    {
        id:4,
        name:"Historia",
        icon:"book"
    },
    {
        id:5,
        name:"Programación",
        icon:"code-slash"
    },
    {
        id:6,
        name:"Actuación",
        icon:"tv"
    },
    {
        id:7,
        name:"Diseño",
        icon:"logo-designernews"
    },
    {
        id:8,
        name:"Edición",
        icon:"play"
    },
    {
        id:9,
        name:"Mecánica",
        icon:"ios-build"
    },
    {
        id:10,
        name:"Finanzas",
        icon:"ios-calculator"
    }
]